version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: maik-db-local
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=maik
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: maik-redis-local
    restart: always
    ports:
      - "6379:6379"

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: maik-meili-local
    restart: always
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=maik-meilisearch-master-key-2026

volumes:
  postgres_data:
